module.exports = {

    "RECIPE_EN_US" : {
        "Masala Chai": "to make 1 cup of masala chai, take 1 cup of whole milk, 1 tablespoon of black tea leaves, sugar as per your taste. Crush quarter inch of fresh ginger root, one cardamom pod. Boil the milk with sugar, ginger and cardamom. When it comes to a boil put the tea leaves and let it boil for a minute or two depending on how strong you like your tea. Strain in a cup and enjoy your hot masala chai!",
        "masala fish fry": "to make masala fish fry, take a firm fish fillet such as tilapia loin. marinade the fish with turmeric, salt, red chilli powder and a pinh of garam masala powder. Marinade for 30 min. Heat 1 table spoon of oil in a non stick fry pan. place the marinated fish gently. Fry each side for 5 to 7 minute on medium heat. Enjoy with some rice and daal!",
        "masala oatmeal": "To make masala oat meal, take 2 table spoon of quick cooking oats in a high edge microwavable bowl. Add 3/4 cup of water, salt to taste, pinch of turmeric powder, cumin powder, coriander powder. Microwave on high heat for 1 minute. Stir the oatmeal, cook for few more cycles of 1 minute cooking followed by stirring the oatmeal in between. Add some butter or ghee to add more taste, enjoy savory oatmeal!",
        "basic daal" : " To make basic daal, take one fourth cup of red lentils. Put it in a pressure cooker with a cup of water. Add some turmeric, salt and green chillies. Pressure cook it for 2 whistles. Once the cooker cools off, take the boiled daal out. In a deep fry pan, heat some ghee or clarified butter. Add some panch phoron, sliced shallots, green chillies whole , let it fry until the onions are golden brown. Pour the boiled daal, taste to adjust salt. Let it boil for 5 to 7 min. Garnish with some chopped cilantro, enjoy hot daal with some roti or rice!"
        "curry base" : "To make basic curry base. Get 1 medium sized onion, 10 to 12 cloves of garlic, half an inch of ginger, few green chillies and 2 tomatoes. Make a smooth paste out of the onion, garlic, ginger and tomatoes in a blender. In a deep fry pan add a tablespoon of  clarified butter. Add 1 teaspoon of whole cumin seeds,add 5 to 10 whole black pepper corn, half inch of cinnamon stick. Let the whole spices roast a bit in ghee. Add the blended tomatoes with onion, ginger garlic in the hot ghee. Add salt to taste, 1 teaspoon of turmeric, 1 teaspoon of cumin powder, 1 teaspoon of coriander powder, 1 teaspoon of garam masala powder and stir everything to incorporate. Lower the heat and let it simmer until oil separates from the mixture. Once you see oil separate your curry base is ready. You can use this for many different dishes from chicken curry to chana masala to fish curry to matar paneer! Enjoy experimenting!",
        "begun bhaja" : "Take some japanese egg plant. Cut it into half along the length. Cut into 4 to 5 inch long slices. Sprinkle some turmeric and salt to the eggplant cuts, toss it in the spice mix. In a shallow non stick fry pan, heat some oil and place the eggplant flesh side down, fry each side until golden brown. Enjoy as a side dish with some hot rice and daal. Happy eating!",
        "masala omelete" : "Take 2 to 3 eggs. Chop some onions, tomatoes, green chillies. Beat the eggs in a bowl add the chopped veggies. Add some salt, turmeric and red chilli powder to the egg mixture. Mix it well. Heat some oil or butter in a shallow non stick fry pan, add the egg mixture and let it set in a low to medium heat.Once the egg sets with no runny egg remaining, Flip to the other side and let it cook on the other side. Let it cook for a minute. Slide into a plate, garnish with some fresh coriander. With some warm toast, enjoy the omelete! Happy eating!"
     }
};
